import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/menu/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WebApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="app-layout-stacked-side flex flex-auto flex-col p-25">
          <div className="flex flex-auto min-w-0">
            <div className="flex flex-col flex-auto min-h-screen min-w-0 relative w-full">
              <header className="header shadow dark:shadow-2xl">
                <Header />
              </header>
              <div className="h-full flex flex-auto flex-col">
                <div className="h-full flex flex-auto flex-col justify between">
                  <main className="h-full">{children}</main>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
